name: Publish
on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: 16.x

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}
      - name: Install packages
        run: yarn install --immutable
      - name: Publish
        run: yarn run publish
